name: Build and push Docker image

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from package.json
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Check if image with version already exists
        run: |
          if curl --silent --fail --location "https://ghcr.io/v2/linusromland/geobot/manifests/${{ env.VERSION }}" > /dev/null; then
            echo "IMAGE_EXISTS=yes" >> $GITHUB_ENV
          else
            echo "IMAGE_EXISTS=no" >> $GITHUB_ENV
          fi
      - name: Build and Push Image
        if: env.IMAGE_EXISTS == 'no'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/linusromland/geobot:latest
            ghcr.io/linusromland/geobot:${{ env.VERSION }}
